[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake_v2 = "tsXqrLjaTSNeyCEMTBAHPZkyDvxRHBuv1t29f3rkZpz"
yield_generator = "EKHVBmv9LcrRC64ryycKWphdkVdM1k2sVETbBvgSxCrf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
